# Generated by Django 5.1.7 on 2025-10-22 01:29

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('REPARTIDOR', 'Repartidor'), ('PROVEEDOR', 'Proveedor'), ('ADMINISTRADOR', 'Administrador')], default='USUARIO', help_text='Define los permisos y accesos del usuario', max_length=20, verbose_name='Rol del usuario')),
                ('first_name', models.CharField(help_text='Nombre del usuario', max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido del usuario', max_length=150, verbose_name='Apellido')),
                ('username', models.CharField(error_messages={'unique': 'Este nombre de usuario ya está en uso.'}, help_text='Nombre de usuario único', max_length=150, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, help_text='Email único para login', max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('celular', models.CharField(help_text='Formato: 09XXXXXXXX (Ecuador)', max_length=10, validators=[django.core.validators.RegexValidator(message='El celular debe comenzar con 09 y tener 10 dígitos', regex='^09\\d{8}$')], verbose_name='Número de celular')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Opcional: Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de nacimiento')),
                ('terminos_aceptados', models.BooleanField(default=False, help_text='Usuario acepta términos y condiciones', verbose_name='Términos y condiciones')),
                ('terminos_fecha_aceptacion', models.DateTimeField(blank=True, help_text='Fecha y hora cuando el usuario aceptó los términos', null=True, verbose_name='Fecha de aceptación de términos')),
                ('terminos_version_aceptada', models.CharField(blank=True, default='1.0', help_text='Versión de los términos y condiciones aceptados', max_length=10, null=True, verbose_name='Versión de términos aceptada')),
                ('terminos_ip_aceptacion', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se aceptaron los términos', null=True, verbose_name='IP de aceptación')),
                ('notificaciones_email', models.BooleanField(default=True, help_text='Si está desactivado, no recibirá correos de la plataforma', verbose_name='Recibir notificaciones por email')),
                ('notificaciones_marketing', models.BooleanField(default=True, help_text='Promociones, ofertas especiales y novedades', verbose_name='Recibir emails de marketing')),
                ('notificaciones_pedidos', models.BooleanField(default=True, help_text='Actualizaciones sobre el estado de pedidos', verbose_name='Notificaciones de pedidos')),
                ('notificaciones_push', models.BooleanField(default=True, help_text='Notificaciones push en la aplicación móvil', verbose_name='Notificaciones push')),
                ('google_picture', models.URLField(blank=True, help_text='URL de la foto de perfil de Google', null=True, verbose_name='Foto de Google')),
                ('vehiculo', models.CharField(blank=True, help_text='Tipo de vehículo del repartidor', max_length=100, null=True, verbose_name='Vehículo')),
                ('placa_vehiculo', models.CharField(blank=True, help_text='Placa del vehículo (formato ecuatoriano: ABC-1234)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido. Use: ABC-1234 o ABC-123', regex='^[A-Z]{3}-\\d{3,4}$')], verbose_name='Placa del vehículo')),
                ('licencia_conducir', models.CharField(blank=True, help_text='Número de licencia de conducir', max_length=50, null=True, verbose_name='Licencia de conducir')),
                ('disponible', models.BooleanField(default=True, help_text='Indica si el repartidor está disponible', verbose_name='Disponible')),
                ('nombre_negocio', models.CharField(blank=True, help_text='Nombre comercial del proveedor', max_length=200, null=True, verbose_name='Nombre del negocio')),
                ('ruc', models.CharField(blank=True, help_text='Registro Único de Contribuyentes (13 dígitos)', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener exactamente 13 dígitos', regex='^\\d{13}$')], verbose_name='RUC')),
                ('direccion_negocio', models.TextField(blank=True, help_text='Dirección física del negocio', null=True, verbose_name='Dirección del negocio')),
                ('categoria_negocio', models.CharField(blank=True, help_text='Tipo de productos/servicios que ofrece', max_length=100, null=True, verbose_name='Categoría del negocio')),
                ('verificado', models.BooleanField(default=False, help_text='Indica si el proveedor ha sido verificado por el admin', verbose_name='Verificado')),
                ('reset_password_code', models.CharField(blank=True, help_text='Hash del código de 6 dígitos para resetear contraseña', max_length=128, null=True, verbose_name='Código de recuperación (hasheado)')),
                ('reset_password_expire', models.DateTimeField(blank=True, db_index=True, help_text='Fecha límite para usar el código (15 minutos)', null=True, verbose_name='Expiración del código')),
                ('reset_password_attempts', models.IntegerField(default=0, help_text='Contador de intentos fallidos al verificar código de recuperación', verbose_name='Intentos de verificación del código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cuenta_desactivada', models.BooleanField(default=False, help_text='Usuario desactivó su cuenta voluntariamente', verbose_name='Cuenta desactivada')),
                ('fecha_desactivacion', models.DateTimeField(blank=True, help_text='Fecha cuando el usuario desactivó su cuenta', null=True, verbose_name='Fecha de desactivación')),
                ('razon_desactivacion', models.TextField(blank=True, help_text='Motivo por el cual el usuario desactivó su cuenta', null=True, verbose_name='Razón de desactivación')),
                ('intentos_login_fallidos', models.IntegerField(default=0, help_text='Contador de intentos fallidos de inicio de sesión', verbose_name='Intentos de login fallidos')),
                ('cuenta_bloqueada_hasta', models.DateTimeField(blank=True, help_text='Fecha hasta la cual la cuenta está temporalmente bloqueada', null=True, verbose_name='Cuenta bloqueada hasta')),
                ('ultimo_login_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP del último inicio de sesión exitoso', null=True, verbose_name='IP del último login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['celular'], name='users_celular_e83223_idx'), models.Index(fields=['rol'], name='users_rol_e53ae1_idx'), models.Index(fields=['cuenta_desactivada'], name='users_cuenta__e71bd5_idx'), models.Index(fields=['ruc'], name='users_ruc_337bf9_idx'), models.Index(fields=['verificado', 'rol'], name='users_verific_afd57d_idx'), models.Index(fields=['disponible', 'rol'], name='users_disponi_6fec59_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
