# Generated by Django 5.1.7 on 2025-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_rol_e53ae1_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_ruc_337bf9_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_verific_afd57d_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_disponi_6fec59_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='categoria_negocio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='direccion_negocio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='licencia_conducir',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre_negocio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notificaciones_pedidos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='placa_vehiculo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ruc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='user',
            name='rol_activo',
            field=models.CharField(choices=[('USUARIO', 'Usuario Normal'), ('PROVEEDOR', 'Proveedor'), ('REPARTIDOR', 'Repartidor'), ('ADMINISTRADOR', 'Administrador')], db_index=True, default='USUARIO', help_text='Rol con el que está operando actualmente', max_length=20, verbose_name='Rol Activo'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles_adicionales',
            field=models.JSONField(blank=True, default=list, help_text='Lista de roles adicionales activos (además del rol principal)', verbose_name='Roles Adicionales'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('USUARIO', 'Usuario Normal'), ('PROVEEDOR', 'Proveedor'), ('REPARTIDOR', 'Repartidor'), ('ADMINISTRADOR', 'Administrador')], db_index=True, default='USUARIO', help_text='Rol principal del usuario', max_length=20, verbose_name='Rol Principal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verificado',
            field=models.BooleanField(db_index=True, default=False, help_text='Si el usuario ha sido verificado por un administrador', verbose_name='Usuario Verificado'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['reset_password_expire'], name='users_reset_p_430be9_idx'),
        ),
    ]
