# Generated by Django 5.1.7 on 2025-11-19 22:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_users_rol_e53ae1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Formato internacional (ej: +593991234567 o +52...)', max_length=128, null=True, region='EC', verbose_name='Número de celular'),
        ),
    ]
