# Generated by Django 5.1.7 on 2025-10-22 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social', max_length=200, verbose_name='Nombre del Proveedor')),
                ('ruc', models.CharField(help_text='RUC o cédula del proveedor', max_length=13, unique=True, verbose_name='RUC/Cédula')),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el formato: '+593999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('tipo_proveedor', models.CharField(choices=[('restaurante', 'Restaurante'), ('farmacia', 'Farmacia'), ('supermercado', 'Supermercado'), ('tienda', 'Tienda'), ('otro', 'Otro')], default='restaurante', max_length=50, verbose_name='Tipo de Proveedor')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del negocio', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si el proveedor está activo en la plataforma', verbose_name='Activo')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de comisión por pedido', max_digits=5, verbose_name='Comisión (%)')),
                ('horario_apertura', models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura')),
                ('horario_cierre', models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='proveedores/logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ruc'], name='proveedores_ruc_a5d69c_idx'), models.Index(fields=['activo'], name='proveedores_activo_068092_idx'), models.Index(fields=['tipo_proveedor'], name='proveedores_tipo_pr_68a632_idx')],
            },
        ),
    ]
