# Generated by Django 5.1.7 on 2025-10-28 04:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Si está lleno, el proveedor está eliminado (soft delete)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario vinculado al proveedor (creado al registrarse)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='verificado',
            field=models.BooleanField(db_index=True, default=False, help_text='Si el proveedor ha sido verificado por un administrador', verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Si el proveedor está activo en la plataforma', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, help_text='⚠️ DEPRECADO: Se sincroniza con user.email', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(db_index=True, help_text='RUC o cédula del proveedor (13 dígitos)', max_length=13, unique=True, verbose_name='RUC/Cédula'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, help_text='⚠️ DEPRECADO: Se sincroniza con user.celular', max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el formato: '+593999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('farmacia', 'Farmacia'), ('supermercado', 'Supermercado'), ('tienda', 'Tienda'), ('otro', 'Otro')], db_index=True, default='restaurante', max_length=50, verbose_name='Tipo de Proveedor'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['verificado'], name='proveedores_verific_c1a941_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['user'], name='proveedores_user_id_bf93a3_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['ciudad'], name='proveedores_ciudad_68ba84_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['deleted_at'], name='proveedores_deleted_fd0d56_idx'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_proveedor'),
        ),
    ]
