# Generated by Django 5.1.7 on 2025-10-30 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ej: Rifa Noviembre 2024', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(help_text='Descripción del premio y condiciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen promocional de la rifa', null=True, upload_to='rifas/%Y/%m/', verbose_name='Imagen del Premio')),
                ('premio', models.CharField(help_text='Descripción del premio', max_length=300, verbose_name='Premio')),
                ('valor_premio', models.DecimalField(decimal_places=2, default=0, help_text='Valor estimado del premio en dólares', max_digits=10, verbose_name='Valor del Premio')),
                ('fecha_inicio', models.DateTimeField(help_text='Inicio de la rifa (1ro del mes)', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fin de la rifa (último día del mes)', verbose_name='Fecha de Fin')),
                ('fecha_sorteo', models.DateTimeField(blank=True, help_text='Cuándo se realizó el sorteo', null=True, verbose_name='Fecha del Sorteo')),
                ('pedidos_minimos', models.PositiveIntegerField(default=3, help_text='Cantidad mínima de pedidos para participar', verbose_name='Pedidos Mínimos')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], db_index=True, default='activa', max_length=20, verbose_name='Estado')),
                ('mes', models.PositiveIntegerField(db_index=True, help_text='Mes de la rifa (1-12)', verbose_name='Mes')),
                ('anio', models.PositiveIntegerField(db_index=True, help_text='Año de la rifa', verbose_name='Año')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(help_text='Admin que creó la rifa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('ganador', models.ForeignKey(blank=True, help_text='Usuario ganador del sorteo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_ganadas', to=settings.AUTH_USER_MODEL, verbose_name='Ganador')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
                'db_table': 'rifas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ganador', models.BooleanField(default=False, help_text='Indica si este usuario ganó', verbose_name='Ganador')),
                ('pedidos_completados', models.PositiveIntegerField(default=0, help_text='Cantidad de pedidos al momento del sorteo', verbose_name='Pedidos Completados')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_rifas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='rifas.rifa', verbose_name='Rifa')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'db_table': 'rifas_participaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='rifa',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='rifas_estado_72482b_idx'),
        ),
        migrations.AddIndex(
            model_name='rifa',
            index=models.Index(fields=['mes', 'anio'], name='rifas_mes_2b5702_idx'),
        ),
        migrations.AddIndex(
            model_name='rifa',
            index=models.Index(fields=['-fecha_inicio'], name='rifas_fecha_i_13fc4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='rifa',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('mes', 'anio', 'estado'), name='una_rifa_activa_por_mes'),
        ),
        migrations.AddIndex(
            model_name='participacion',
            index=models.Index(fields=['rifa', 'usuario'], name='rifas_parti_rifa_id_9f05ef_idx'),
        ),
        migrations.AddIndex(
            model_name='participacion',
            index=models.Index(fields=['ganador'], name='rifas_parti_ganador_47ab17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together={('rifa', 'usuario')},
        ),
    ]
