# Generated by Django 5.1.7 on 2025-10-22 01:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('repartidores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proveedor', 'Pedido de Proveedor'), ('directo', 'Encargo Directo')], default='proveedor', max_length=20)),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Lo que el cliente necesita si es encargo directo.')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('direccion_origen', models.TextField(blank=True, null=True)),
                ('direccion_entrega', models.TextField()),
                ('metodo_pago', models.CharField(default='efectivo', max_length=30)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True)),
                ('cancelado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('aceptado_por_repartidor', models.BooleanField(default=False)),
                ('confirmado_por_proveedor', models.BooleanField(default=False)),
                ('comision_repartidor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('comision_proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ganancia_app', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuarios.perfil')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='proveedores.proveedor')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en'], name='pedidos_ped_creado__9e8b13_idx'), models.Index(fields=['estado'], name='pedidos_ped_estado_20cbc4_idx'), models.Index(fields=['tipo'], name='pedidos_ped_tipo_ed4e80_idx')],
            },
        ),
    ]
