# Generated by Django 5.1.7 on 2025-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('repartidores', '0001_initial'),
        ('usuarios', '0003_alter_direccionfavorita_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitud_destino',
            field=models.FloatField(blank=True, help_text='Latitud de la dirección de entrega', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='latitud_origen',
            field=models.FloatField(blank=True, help_text='Latitud del punto de origen', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud_destino',
            field=models.FloatField(blank=True, help_text='Longitud de la dirección de entrega', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud_origen',
            field=models.FloatField(blank=True, help_text='Longitud del punto de origen', null=True),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['latitud_destino', 'longitud_destino'], name='pedidos_ped_latitud_a66338_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('latitud_destino__isnull', True), models.Q(('latitud_destino__gte', -5.0), ('latitud_destino__lte', 2.0)), _connector='OR'), name='pedido_lat_destino_ecuador'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('longitud_destino__isnull', True), models.Q(('longitud_destino__gte', -92.0), ('longitud_destino__lte', -75.0)), _connector='OR'), name='pedido_lon_destino_ecuador'),
        ),
    ]
