# Generated by Django 5.1.7 on 2025-10-29 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_latitud_destino_pedido_latitud_origen_and_more'),
        ('proveedores', '0002_proveedor_deleted_at_proveedor_user_and_more'),
        ('repartidores', '0001_initial'),
        ('usuarios', '0003_alter_direccionfavorita_etiqueta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha del Cambio')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el cambio', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Historial de Pedido',
                'verbose_name_plural': 'Historial de Pedidos',
                'db_table': 'pedidos_historial',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='MetricasPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_pedidos', models.IntegerField(default=0, verbose_name='Total de Pedidos')),
                ('pedidos_entregados', models.IntegerField(default=0, verbose_name='Pedidos Entregados')),
                ('pedidos_cancelados', models.IntegerField(default=0, verbose_name='Pedidos Cancelados')),
                ('ingresos_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos del Día')),
                ('ganancia_app', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganancia de la App')),
                ('ticket_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ticket Promedio')),
                ('tiempo_promedio_entrega', models.IntegerField(default=0, verbose_name='Tiempo Promedio de Entrega (minutos)')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Métrica de Pedidos',
                'verbose_name_plural': 'Métricas de Pedidos',
                'db_table': 'pedidos_metricas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RenameIndex(
            model_name='pedido',
            new_name='pedidos_creado__7b0104_idx',
            old_name='pedidos_ped_creado__9e8b13_idx',
        ),
        migrations.RenameIndex(
            model_name='pedido',
            new_name='pedidos_estado_b14829_idx',
            old_name='pedidos_ped_estado_20cbc4_idx',
        ),
        migrations.RenameIndex(
            model_name='pedido',
            new_name='pedidos_tipo_fbe431_idx',
            old_name='pedidos_ped_tipo_ed4e80_idx',
        ),
        migrations.RenameIndex(
            model_name='pedido',
            new_name='pedidos_latitud_0c558b_idx',
            old_name='pedidos_ped_latitud_a66338_idx',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='aceptado_por_repartidor',
            field=models.BooleanField(default=False, help_text='Indica si un repartidor aceptó el pedido', verbose_name='Aceptado por Repartidor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cancelado_por',
            field=models.CharField(blank=True, help_text='Actor que canceló el pedido (cliente, proveedor, repartidor, admin)', max_length=50, null=True, verbose_name='Cancelado Por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que realiza el pedido', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuarios.perfil', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comision_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que recibe el proveedor', max_digits=6, verbose_name='Comisión Proveedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comision_repartidor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que recibe el repartidor', max_digits=6, verbose_name='Comisión Repartidor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='confirmado_por_proveedor',
            field=models.BooleanField(default=False, help_text='Indica si el proveedor confirmó la preparación', verbose_name='Confirmado por Proveedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del pedido (requerido para encargos directos)', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(help_text='Dirección donde se entregará el pedido', verbose_name='Dirección de Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_origen',
            field=models.TextField(blank=True, help_text='Dirección del proveedor o punto de recogida', null=True, verbose_name='Dirección de Origen'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='confirmado', help_text='Estado actual del pedido', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se entregó el pedido', null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ganancia_app',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión de la aplicación', max_digits=6, verbose_name='Ganancia App'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='latitud_destino',
            field=models.FloatField(blank=True, help_text='Latitud de la dirección de entrega', null=True, verbose_name='Latitud Destino'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='latitud_origen',
            field=models.FloatField(blank=True, help_text='Latitud del punto de origen (-5.0 a 2.0 para Ecuador)', null=True, verbose_name='Latitud Origen'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='longitud_destino',
            field=models.FloatField(blank=True, help_text='Longitud de la dirección de entrega', null=True, verbose_name='Longitud Destino'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='longitud_origen',
            field=models.FloatField(blank=True, help_text='Longitud del punto de origen (-92.0 a -75.0 para Ecuador)', null=True, verbose_name='Longitud Origen'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='efectivo', help_text='Forma de pago del pedido', max_length=30, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del pedido (null para encargos directos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, help_text='Repartidor asignado al pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='repartidores.repartidor', verbose_name='Repartidor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('proveedor', 'Pedido de Proveedor'), ('directo', 'Encargo Directo')], default='proveedor', help_text='Tipo: Pedido de Proveedor o Encargo Directo', max_length=20, verbose_name='Tipo de Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total del pedido', max_digits=8, verbose_name='Total'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='pedidos_cliente_e28e20_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['proveedor'], name='pedidos_proveed_5f2615_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['repartidor'], name='pedidos_reparti_99a976_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'repartidor'], name='pedidos_estado_efae5d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'creado_en'], name='pedidos_estado_78c23d_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('latitud_origen__isnull', True), models.Q(('latitud_origen__gte', -5.0), ('latitud_origen__lte', 2.0)), _connector='OR'), name='pedido_lat_origen_ecuador'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('longitud_origen__isnull', True), models.Q(('longitud_origen__gte', -92.0), ('longitud_origen__lte', -75.0)), _connector='OR'), name='pedido_lon_origen_ecuador'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='pedido_total_positivo'),
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó el Cambio'),
        ),
        migrations.AddIndex(
            model_name='historialpedido',
            index=models.Index(fields=['pedido', '-fecha_cambio'], name='pedidos_his_pedido__d7331b_idx'),
        ),
    ]
