# Generated by Django 5.1.7 on 2025-10-30 20:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0002_proveedor_deleted_at_proveedor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', verbose_name='Descripción')),
                ('icono', models.ImageField(blank=True, help_text='Icono representativo de la categoría', null=True, upload_to='categorias/iconos/', verbose_name='Icono')),
                ('orden', models.IntegerField(db_index=True, default=0, help_text='Orden de visualización (menor = primero)', verbose_name='Orden')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si la categoría está visible', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activo'], name='categorias_activo_e09596_idx'), models.Index(fields=['orden'], name='categorias_orden_6e80b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre del producto', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('sku', models.CharField(db_index=True, help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU')),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/', verbose_name='Imagen Principal')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio base del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('stock', models.IntegerField(db_index=True, default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('stock_minimo', models.IntegerField(default=5, help_text='Cantidad mínima antes de alerta', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('controlar_stock', models.BooleanField(default=True, help_text='Si se debe controlar inventario para este producto', verbose_name='Controlar Stock')),
                ('en_oferta', models.BooleanField(db_index=True, default=False, help_text='Si el producto está en oferta', verbose_name='En Oferta')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Oferta')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso del producto en kilogramos', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('tiempo_preparacion', models.IntegerField(default=15, help_text='Tiempo estimado de preparación en minutos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Preparación (min)')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si el producto está disponible para venta', verbose_name='Activo')),
                ('destacado', models.BooleanField(db_index=True, default=False, help_text='Si el producto aparece destacado en la app', verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete', null=True, verbose_name='Fecha de Eliminación')),
                ('categoria', models.ForeignKey(help_text='Categoría del producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria', verbose_name='Categoría')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que ofrece este producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de la imagen', max_length=200, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'db_table': 'producto_imagenes',
                'ordering': ['producto', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la variante (Ej: Grande, 500ml, Familiar)', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la variante', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio específico de esta variante', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('sku_variante', models.CharField(db_index=True, help_text='Código único de la variante', max_length=50, unique=True, verbose_name='SKU Variante')),
                ('stock', models.IntegerField(default=0, help_text='Stock específico de esta variante', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'db_table': 'producto_variantes',
                'ordering': ['producto', 'precio'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['proveedor', 'activo'], name='productos_proveed_a70562_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='productos_categor_6d98d4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='productos_sku_a62667_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='productos_activo_aa3d01_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['en_oferta'], name='productos_en_ofer_8ebe4e_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['destacado'], name='productos_destaca_126203_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['deleted_at'], name='productos_deleted_7df6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='productos_stock_2e1108_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='productoimagen',
            index=models.Index(fields=['producto', 'orden'], name='producto_im_product_866452_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['producto', 'activo'], name='producto_va_product_ea6bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['sku_variante'], name='producto_va_sku_var_996d79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto', 'nombre')},
        ),
    ]
