# Generated by Django 5.1.7 on 2025-10-30 20:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0003_historialpedido_metricaspedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('promocion', 'Promoción'), ('sistema', 'Sistema'), ('repartidor', 'Repartidor')], default='pedido', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=100, verbose_name='Título')),
                ('mensaje', models.TextField(help_text='Contenido de la notificación', verbose_name='Mensaje')),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Información extra en formato JSON', verbose_name='Datos adicionales')),
                ('leida', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('enviada_push', models.BooleanField(default=False, help_text='Indica si se envió notificación push', verbose_name='Enviada por push')),
                ('error_envio', models.TextField(blank=True, help_text='Mensaje de error si falló el envío push', null=True, verbose_name='Error de envío')),
                ('creada_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('pedido', models.ForeignKey(blank=True, help_text='Pedido asociado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='pedidos.pedido', verbose_name='Pedido relacionado')),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['usuario', '-creada_en'], name='notificacio_usuario_65ada8_idx'), models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_ef49b7_idx'), models.Index(fields=['tipo', '-creada_en'], name='notificacio_tipo_583a01_idx'), models.Index(fields=['pedido'], name='notificacio_pedido__aab01b_idx')],
            },
        ),
    ]
