# Generated by Django 5.1.7 on 2025-10-22 01:29

import django.core.validators
import django.db.models.deletion
import usuarios.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionFavorita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('trabajo', 'Trabajo'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de dirección')),
                ('etiqueta', models.CharField(help_text='Ej: Mi casa, Oficina', max_length=50, verbose_name='Etiqueta')),
                ('direccion', models.TextField(verbose_name='Dirección completa')),
                ('referencia', models.CharField(blank=True, help_text='Ej: Casa blanca, portón negro', max_length=200, verbose_name='Referencia')),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('es_predeterminada', models.BooleanField(default=False, verbose_name='Usar como dirección predeterminada')),
                ('activa', models.BooleanField(default=True, verbose_name='Dirección activa')),
                ('veces_usada', models.IntegerField(default=0, verbose_name='Veces utilizada')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección Favorita',
                'verbose_name_plural': 'Direcciones Favoritas',
                'db_table': 'direcciones_favoritas',
                'ordering': ['-es_predeterminada', '-ultimo_uso', '-created_at'],
                'indexes': [models.Index(fields=['user', 'activa'], name='direcciones_user_id_dac6b5_idx'), models.Index(fields=['es_predeterminada'], name='direcciones_es_pred_0ee1a9_idx'), models.Index(fields=['user', 'activa', 'es_predeterminada'], name='direcciones_user_id_f31fe7_idx')],
                'unique_together': {('user', 'etiqueta')},
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Tipo de pago')),
                ('alias', models.CharField(help_text='Ej: Pago en efectivo, Transferencia Banco Pichincha', max_length=50, verbose_name='Nombre')),
                ('comprobante_pago', models.ImageField(blank=True, help_text='Imagen del comprobante (obligatorio para transferencias)', null=True, upload_to='comprobantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), usuarios.models.validar_tamano_imagen], verbose_name='Comprobante de transferencia')),
                ('observaciones', models.CharField(blank=True, help_text='Describe cualquier problema que haya ocurrido (máx. 100 caracteres)', max_length=100, verbose_name='Observaciones')),
                ('es_predeterminado', models.BooleanField(default=False, verbose_name='Método predeterminado')),
                ('activo', models.BooleanField(default=True, verbose_name='Método activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodos_pago',
                'ordering': ['-es_predeterminado', '-created_at'],
                'indexes': [models.Index(fields=['user', 'activo'], name='metodos_pag_user_id_718a88_idx'), models.Index(fields=['tipo'], name='metodos_pag_tipo_a0683f_idx'), models.Index(fields=['user', 'tipo', 'activo'], name='metodos_pag_user_id_678b9d_idx')],
                'unique_together': {('user', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), usuarios.models.validar_tamano_imagen], verbose_name='Foto de perfil')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono de contacto')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fcm_token', models.CharField(blank=True, db_index=True, help_text='Token de Firebase Cloud Messaging del dispositivo', max_length=255, null=True, verbose_name='Token FCM para notificaciones push')),
                ('fcm_token_actualizado', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización del token FCM')),
                ('calificacion', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Calificación promedio')),
                ('total_resenas', models.IntegerField(default=0, verbose_name='Total de reseñas')),
                ('total_pedidos', models.IntegerField(default=0, verbose_name='Total de pedidos realizados')),
                ('pedidos_mes_actual', models.IntegerField(default=0, help_text='Se resetea cada mes. Mínimo 3 para participar en rifa', verbose_name='Pedidos del mes actual')),
                ('ultima_actualizacion_mes', models.DateField(auto_now_add=True, verbose_name='Última actualización de mes')),
                ('participa_en_sorteos', models.BooleanField(default=True, verbose_name='Participa en sorteos automáticos')),
                ('notificaciones_pedido', models.BooleanField(default=True, verbose_name='Notificaciones de estado del pedido')),
                ('notificaciones_promociones', models.BooleanField(default=True, verbose_name='Recibir ofertas y promociones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'perfiles_usuario',
                'indexes': [models.Index(fields=['calificacion'], name='perfiles_us_calific_1c3bde_idx'), models.Index(fields=['pedidos_mes_actual'], name='perfiles_us_pedidos_2df090_idx'), models.Index(fields=['fcm_token'], name='perfiles_us_fcm_tok_18fbfe_idx'), models.Index(fields=['user', 'participa_en_sorteos'], name='perfiles_us_user_id_32b23b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UbicacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_actual', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicación de Usuario',
                'verbose_name_plural': 'Ubicaciones de Usuarios',
                'db_table': 'ubicaciones_usuario',
                'indexes': [models.Index(fields=['user'], name='ubicaciones_user_id_3e70b8_idx'), models.Index(fields=['actualizado_en'], name='ubicaciones_actuali_c79395_idx')],
            },
        ),
    ]
