# Generated by Django 5.1.7 on 2025-10-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
    ]
