# Generated by Django 5.1.7 on 2025-10-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionfavorita',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Ej: Mi casa, Oficina', max_length=50, verbose_name='Etiqueta'),
        ),
    ]
