# Generated by Django 5.1.7 on 2025-11-12 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_direccionfavorita_etiqueta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioRol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_solicitado', models.CharField(choices=[('PROVEEDOR', 'Quiero ser Proveedor'), ('REPARTIDOR', 'Quiero ser Repartidor')], max_length=20, verbose_name='Rol Solicitado')),
                ('motivo', models.TextField(help_text='¿Por qué deseas cambiar de rol?', max_length=500, verbose_name='Motivo de la Solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('motivo_respuesta', models.TextField(blank=True, help_text='Comentario del admin al aceptar/rechazar', verbose_name='Motivo de la Respuesta')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Solicitud')),
                ('respondido_en', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Respuesta')),
                ('admin_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_rol_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Admin Responsable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_rol', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Rol',
                'verbose_name_plural': 'Solicitudes de Cambio de Rol',
                'db_table': 'solicitudes_cambio_rol',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['user', 'estado'], name='solicitudes_user_id_f5bb53_idx'), models.Index(fields=['estado', '-creado_en'], name='solicitudes_estado_85023f_idx'), models.Index(fields=['admin_responsable', '-respondido_en'], name='solicitudes_admin_r_eb5cfa_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('user', 'rol_solicitado'), name='una_solicitud_pendiente_por_rol')],
            },
        ),
    ]
