# Generated by Django 5.1.7 on 2025-11-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_solicitudcambiorol'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='cedula_identidad',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='descripcion_negocio',
            field=models.TextField(blank=True, verbose_name='Descripción del Negocio'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='disponibilidad',
            field=models.JSONField(blank=True, default=dict, help_text='Horarios de disponibilidad (formato JSON)', verbose_name='Disponibilidad'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='horario_apertura',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='horario_cierre',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='ruc',
            field=models.CharField(blank=True, db_index=True, help_text='RUC de 13 dígitos (solo para proveedores)', max_length=13, null=True, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='tipo_negocio',
            field=models.CharField(blank=True, choices=[('restaurante', 'Restaurante'), ('farmacia', 'Farmacia'), ('supermercado', 'Supermercado'), ('tienda', 'Tienda'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Negocio'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('bicicleta', 'Bicicleta'), ('moto', 'Moto'), ('auto', 'Auto'), ('camion', 'Camión'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Vehículo'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='zona_cobertura',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zona de Cobertura'),
        ),
    ]
