# Generated by Django 5.1.7 on 2025-11-17 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_solicitudcambiorol_cedula_identidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='motivo_reversion',
            field=models.TextField(blank=True, help_text='Razón por la que se revirtió el cambio de rol', verbose_name='Motivo de la Reversión'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='revertido_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Reversión'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='revertido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_rol_revertidas', to=settings.AUTH_USER_MODEL, verbose_name='Admin que Revirtió'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='rol_anterior',
            field=models.CharField(blank=True, db_index=True, help_text='Rol que tenía el usuario antes del cambio', max_length=20, verbose_name='Rol Anterior'),
        ),
        migrations.AlterField(
            model_name='solicitudcambiorol',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('REVERTIDA', 'Revertida')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
