# Generated by Django 5.1.7 on 2025-10-30 20:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, help_text='Ej: Administrador General, Supervisor', max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, help_text='Ej: Operaciones, Finanzas', max_length=100, verbose_name='Departamento')),
                ('puede_gestionar_usuarios', models.BooleanField(default=True, verbose_name='Puede gestionar usuarios')),
                ('puede_gestionar_pedidos', models.BooleanField(default=True, verbose_name='Puede gestionar pedidos')),
                ('puede_gestionar_proveedores', models.BooleanField(default=True, verbose_name='Puede gestionar proveedores')),
                ('puede_gestionar_repartidores', models.BooleanField(default=True, verbose_name='Puede gestionar repartidores')),
                ('puede_gestionar_rifas', models.BooleanField(default=True, verbose_name='Puede gestionar rifas')),
                ('puede_ver_reportes', models.BooleanField(default=True, verbose_name='Puede ver reportes')),
                ('puede_configurar_sistema', models.BooleanField(default=False, help_text='Solo super administradores', verbose_name='Puede configurar sistema')),
                ('activo', models.BooleanField(default=True, help_text='Si el administrador está activo', verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administradores',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AccionAdministrativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('crear_usuario', 'Crear Usuario'), ('editar_usuario', 'Editar Usuario'), ('desactivar_usuario', 'Desactivar Usuario'), ('activar_usuario', 'Activar Usuario'), ('cambiar_rol', 'Cambiar Rol'), ('resetear_password', 'Resetear Contraseña'), ('verificar_proveedor', 'Verificar Proveedor'), ('rechazar_proveedor', 'Rechazar Proveedor'), ('desactivar_proveedor', 'Desactivar Proveedor'), ('verificar_repartidor', 'Verificar Repartidor'), ('rechazar_repartidor', 'Rechazar Repartidor'), ('desactivar_repartidor', 'Desactivar Repartidor'), ('cancelar_pedido', 'Cancelar Pedido'), ('reasignar_pedido', 'Reasignar Pedido'), ('editar_pedido', 'Editar Pedido'), ('crear_rifa', 'Crear Rifa'), ('realizar_sorteo', 'Realizar Sorteo'), ('cancelar_rifa', 'Cancelar Rifa'), ('configurar_sistema', 'Configurar Sistema'), ('notificacion_masiva', 'Notificación Masiva'), ('exportar_datos', 'Exportar Datos')], db_index=True, max_length=50, verbose_name='Tipo de Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción', verbose_name='Descripción')),
                ('modelo_afectado', models.CharField(blank=True, help_text='Ej: User, Pedido, Proveedor', max_length=100, verbose_name='Modelo Afectado')),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto afectado', max_length=100, verbose_name='ID del Objeto')),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, help_text='Estado anterior del objeto (opcional)', verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, default=dict, help_text='Nuevo estado del objeto (opcional)', verbose_name='Datos Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('exitosa', models.BooleanField(default=True, verbose_name='Acción Exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Si la acción falló', verbose_name='Mensaje de Error')),
                ('fecha_accion', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de la Acción')),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='administradores.administrador', verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Acción Administrativa',
                'verbose_name_plural': 'Acciones Administrativas',
                'db_table': 'acciones_administrativas',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_app_proveedor', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje que se lleva la app de pedidos de proveedor', max_digits=5, verbose_name='Comisión App - Pedidos Proveedor (%)')),
                ('comision_app_directo', models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje que se lleva la app de encargos directos', max_digits=5, verbose_name='Comisión App - Encargos Directos (%)')),
                ('comision_repartidor_proveedor', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Comisión Repartidor - Pedidos Proveedor (%)')),
                ('comision_repartidor_directo', models.DecimalField(decimal_places=2, default=85.0, max_digits=5, verbose_name='Comisión Repartidor - Encargos Directos (%)')),
                ('pedidos_minimos_rifa', models.PositiveIntegerField(default=3, help_text='Cantidad mínima de pedidos para participar en rifa', verbose_name='Pedidos Mínimos para Rifa')),
                ('pedido_maximo', models.DecimalField(decimal_places=2, default=1000.0, help_text='Monto máximo permitido por pedido', max_digits=10, verbose_name='Monto Máximo por Pedido')),
                ('pedido_minimo', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Monto Mínimo por Pedido')),
                ('tiempo_maximo_entrega', models.PositiveIntegerField(default=60, help_text='Tiempo límite para marcar un pedido como retrasado', verbose_name='Tiempo Máximo de Entrega (minutos)')),
                ('telefono_soporte', models.CharField(blank=True, max_length=15, verbose_name='Teléfono de Soporte')),
                ('email_soporte', models.EmailField(blank=True, max_length=254, verbose_name='Email de Soporte')),
                ('mantenimiento', models.BooleanField(default=False, help_text='Si está activado, solo admins pueden acceder', verbose_name='Modo Mantenimiento')),
                ('mensaje_mantenimiento', models.TextField(blank=True, verbose_name='Mensaje de Mantenimiento')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administradores.administrador', verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.AddIndex(
            model_name='administrador',
            index=models.Index(fields=['user'], name='administrad_user_id_f55cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='administrador',
            index=models.Index(fields=['activo'], name='administrad_activo_299c89_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['administrador', '-fecha_accion'], name='acciones_ad_adminis_ed8395_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['tipo_accion', '-fecha_accion'], name='acciones_ad_tipo_ac_b91acf_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['modelo_afectado', 'objeto_id'], name='acciones_ad_modelo__e7a520_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['-fecha_accion'], name='acciones_ad_fecha_a_df658f_idx'),
        ),
    ]
