# Generated by Django 5.1.7 on 2025-11-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0002_administrador_puede_gestionar_solicitudes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionadministrativa',
            name='tipo_accion',
            field=models.CharField(choices=[('crear_usuario', 'Crear Usuario'), ('editar_usuario', 'Editar Usuario'), ('desactivar_usuario', 'Desactivar Usuario'), ('activar_usuario', 'Activar Usuario'), ('cambiar_rol', 'Cambiar Rol'), ('resetear_password', 'Resetear Contraseña'), ('verificar_proveedor', 'Verificar Proveedor'), ('rechazar_proveedor', 'Rechazar Proveedor'), ('desactivar_proveedor', 'Desactivar Proveedor'), ('verificar_repartidor', 'Verificar Repartidor'), ('rechazar_repartidor', 'Rechazar Repartidor'), ('desactivar_repartidor', 'Desactivar Repartidor'), ('cancelar_pedido', 'Cancelar Pedido'), ('reasignar_pedido', 'Reasignar Pedido'), ('editar_pedido', 'Editar Pedido'), ('crear_rifa', 'Crear Rifa'), ('realizar_sorteo', 'Realizar Sorteo'), ('cancelar_rifa', 'Cancelar Rifa'), ('aceptar_solicitud_rol', 'Aceptar Solicitud de Rol'), ('rechazar_solicitud_rol', 'Rechazar Solicitud de Rol'), ('configurar_sistema', 'Configurar Sistema'), ('notificacion_masiva', 'Notificación Masiva'), ('exportar_datos', 'Exportar Datos'), ('revertir_cambio_rol', 'Revertir Cambio de Rol')], db_index=True, max_length=50, verbose_name='Tipo de Acción'),
        ),
    ]
